TIME_LABEL = "Time [days]"
FLUX_LABEL = "Relative Flux [ppt]"
LIGHTCURVE_PLOT = "flux_vs_time.png"
FOLDED_LIGHTCURVE_PLOT = "folded_flux_vs_time.png"
POSTERIOR_PLOT = "posteriors.png"
ECCENTRICITY_PLOT = "eccentricity_posteriors.png"
